services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./
    working_dir: /app
    volumes:
      - ./src:/app/
      - ./vhost.conf:/opt/docker/etc/nginx/vhost.conf
    ports:
      - 9000:9000
      - 80:80
